# Generated by Django 3.0.5 on 2020-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='starting_date',
            field=models.DateField(auto_now=True),
        ),
    ]
