# Generated by Django 3.0.5 on 2020-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_seasons_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
