# Generated by Django 3.0.5 on 2020-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_seasons_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasons',
            old_name='season',
            new_name='name',
        ),
        migrations.AddField(
            model_name='seasons',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
