# Generated by Django 3.0.5 on 2020-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_auto_20200606_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
