# Generated by Django 3.0.5 on 2020-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_organization_players_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltournament',
            name='teams_in_tournament',
            field=models.ManyToManyField(to='api_basic.Team'),
        ),
    ]
