# Generated by Django 3.0.5 on 2020-06-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0011_totaltournament_teams_in_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ingame_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('pubg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('community', models.ManyToManyField(related_name='peoples_roles_in_community', to='api_basic.Community')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ManyToManyField(related_name='organizations_backing_teams', to='api_basic.Organization'),
        ),
        migrations.AlterField(
            model_name='totaltournament',
            name='teams_in_tournament',
            field=models.ManyToManyField(related_name='teams_participating_in_tournaments', to='api_basic.Team'),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.AddField(
            model_name='peoples',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_basic.Team'),
        ),
    ]
