# Generated by Django 3.0.5 on 2020-06-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0013_totaltournament_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organizations',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='organization',
            new_name='organizations',
        ),
    ]
