# Generated by Django 3.0.5 on 2020-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0014_auto_20200607_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='totaltournament',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
