# Generated by Django 3.0.5 on 2020-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0015_auto_20200607_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaltournament',
            options={'verbose_name_plural': 'TotalTournament'},
        ),
        migrations.AddField(
            model_name='totaltournament',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
