# Generated by Django 3.0.5 on 2020-06-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0016_auto_20200607_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totaltournament',
            old_name='teams_in_tournament',
            new_name='teams',
        ),
    ]
