# Generated by Django 3.0.5 on 2020-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0018_remove_totaltournament_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltournament',
            name='teams',
            field=models.ManyToManyField(related_name='teams_participating_in_tournaments', to='api_basic.Teams'),
        ),
    ]
