# Generated by Django 3.0.5 on 2020-06-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0019_totaltournament_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTournament', models.ManyToManyField(to='api_basic.TotalTournament')),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_stating_time', models.DateTimeField(blank=True, null=True)),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_basic.Days')),
                ('maps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_basic.Maps')),
            ],
        ),
    ]
