# Generated by Django 3.0.5 on 2020-06-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0020_days_maps_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='maps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.Maps'),
        ),
    ]
