# Generated by Django 3.0.5 on 2020-06-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0022_auto_20200607_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltournament',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basic.Seasons'),
        ),
    ]
