# Generated by Django 3.0.5 on 2020-06-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0023_auto_20200607_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name_plural': 'Days'},
        ),
        migrations.AlterModelOptions(
            name='maps',
            options={'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='results',
        ),
        migrations.AddField(
            model_name='results',
            name='matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basic.Matches'),
        ),
        migrations.AlterField(
            model_name='results',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basic.Teams'),
        ),
    ]
