# Generated by Django 3.0.5 on 2020-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0025_pointstable_pointstabletype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstable',
            options={'verbose_name_plural': 'PointsTable'},
        ),
        migrations.AlterModelOptions(
            name='pointstabletype',
            options={'verbose_name_plural': 'PointsTableType'},
        ),
        migrations.AddField(
            model_name='results',
            name='Total_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='kill_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='placement_point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
