# Generated by Django 3.0.5 on 2020-06-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0027_results_points_table_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='total_tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basic.TotalTournament'),
        ),
        migrations.AddField(
            model_name='peoples',
            name='total_damage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='peoples',
            name='total_kills',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='peoples',
            name='total_knockout',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='peoples',
            name='total_matches_played',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
