# Generated by Django 3.0.5 on 2020-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0030_auto_20200610_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='RolesInCommunity',
        ),
        migrations.AlterModelOptions(
            name='rolesincommunity',
            options={'verbose_name_plural': 'RolesInCommunity'},
        ),
        migrations.RemoveField(
            model_name='peoples',
            name='community',
        ),
        migrations.AddField(
            model_name='peoples',
            name='RolesInCommunity',
            field=models.ManyToManyField(related_name='peoples_roles_in_Community', to='api_basic.RolesInCommunity'),
        ),
    ]
